# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:latest
    working_directory: ~/circleci-deployment
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-deployment
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}
            - yarn-cache-
      - run: yarn install
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .
  test_and_report:
    docker:
      - image: circleci/node:latest
    working_directory: ~/circleci-deployment
    steps:
      - attach_workspace:
        at: ~/circleci-deployment
      - run: CI=true yarn test --coverage --reporters=default --reporters=jest-junit --coverageReporters=text-lcov | ./node_modules/coveralls/bin/coveralls.js
      - store_artifacts:
          path: ./test-results
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/circleci-deployment
    steps:
      - attach_workspace:
          at: ~/circleci-deployment
      - run: yarn install
      - run:
        name: yarn build
  deployment:
    docker:
      - image: circleci/node:latest
    working_directory: ~/circleci-deployment
    steps:
      - attach_workspace:
          at: ~/circleci-deployment
      - run: yarn install
      - deploy:
        name: Deploy & Alias.
        command: yarn run deploy

workflows:
  version: 2
  test_deploy:
    jobs:
      - checkout_code
      - test_and_report:
        requires:
          - checkout_code
      - build:
        requires:
          - test_and_report
      
      - deployment:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - production
