
pipeline {
    agent any
    stages {
        stage('Build'){
            steps {
                sh 'npm run build'
            }
            post {
                success {
                    echo 'Now Archiving'
                    archiveArtifacts artifacts: '**/build'
                }
            }
        }
    }
}
